openapi: '3.0.2'
info:
  title: 주문/취소/반품/교환 모니터링
  description: >-
    주문/취소/반품/교환 모니터링에 대한 REST API 정의
  version: '1.0'
servers:
  - url: https://localhost:8080/{base-path}
    variables:
      base-path:
        default: bo
tags:
  - name: order-orchestrator
    description: 주문/취소/반품/교환 모니터링에 대한 인터페이스 정의
paths:
  /controller/order:
    post:
      tags:
        - order-orchestrator
      summary: 주문처리요청
      description: 주문처리요청을 위한 API
      operationId: requestOrder
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStateDto'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/OrderStateDto'
  /controller/cancel-order:
    post:
      tags:
        - order-orchestrator
      summary: 주문취소처리요청
      description: 주문취소처리요청을 위한 API
      operationId: requestCancelOrder
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCancelStateDto'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/OrderCancelStateDto'
  /controller/return-order:
    post:
      tags:
        - order-orchestrator
      summary: 반품처리요청
      description: 반품처리요청
      operationId: requestReturnOrder
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderReturnStateDto'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/OrderReturnStateDto'
  /controller/exchange-order:
    post:
      tags:
        - order-orchestrator
      summary: 교환처리요청
      description: 교환처리요청
      operationId: requestExchangeOrder
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderExchangeStateDto'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/OrderExchangeStateDto'
  /controller/monitor/dash-board/main/{type}:
    get:
      tags:
        - order-orchestrator
      summary: 주문요청 상태 모니터링, 타입별 메인 대시보드
      description: 주문요청 상태 모니터링, 타입별 메인 대시보드를 확인할 수 있다. 대시보드뷰 상태(ORDER, CANCEL, RETURN, EXCHANGE, COMP)
      operationId: getRequestOrderStatus
      parameters:
        - in: path
          required: true
          name: type
          schema:
            type: string
            description: 대시보드뷰 상태(ORDER, CANCEL, RETURN, EXCHANGE, COMP)
            enum:
              - ORDER
              - CANCEL
              - RETURN
              - EXCHANGE
              - COMP
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SummaryOrderStatusForOrderRequest'
        '405':
          description: Invalid input
  /controller/monitor/dash-board/error:
    get:
      tags:
        - order-orchestrator
      summary: 오류 상세 내역을 조회한다.
      description: 오류 상세 내역을 확인할 수 있다.
      operationId: getErrorOrderStatusDetail
      parameters:
        - in: query
          required: false
          name: startDate
          schema:
            type: string
            description: 시작일시
            format: date-time
        - in: query
          required: false
          name: endDate
          schema:
            type: string
            description: 종료일시
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SummaryErrorOrderStatusDetail'
        '405':
          description: Invalid input
  /controller/monitor/dash-board/retry:
    get:
      tags:
        - order-orchestrator
      summary: 재처리목록을  조회한다.
      description: 재처리목록을  확인할 수 있다.
      operationId: getRetryOrderStatusDetail
      parameters:
        - in: query
          required: false
          name: startDate
          schema:
            type: string
            description: 시작일시
            format: date-time
        - in: query
          required: false
          name: endDate
          schema:
            type: string
            description: 종료일시
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SummaryRetryOrderStatusDetail'
        '405':
          description: Invalid input
  /controller/monitor/dash-board/slow:
    get:
      tags:
        - order-orchestrator
      summary: 재처리목록을  조회한다.
      description: 재처리목록을  확인할 수 있다.
      operationId: getSlowProcessOrderStatusDetail
      parameters:
        - in: query
          required: false
          name: startDate
          schema:
            type: string
            description: 시작일시
            format: date-time
        - in: query
          required: false
          name: endDate
          schema:
            type: string
            description: 종료일시
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SummarySlowProcessOrderStatusDetail'
        '405':
          description: Invalid input


components:
  requestBodies:
    OrderStateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderStateDto'
    OrderCancelStateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderCancelStateDto'
    OrderReturnStateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderReturnStateDto'
    OrderExchangeStateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderExchangeStateDto'
  schemas:
    SummarySlowProcessOrderStatusDetail:
      title: Orchestrator에서 발생한 느린처리의 상세 정보를 조회한다.
      description: Orchestrator에서 발생한 느린처리의 상세 정보를 조회한다.
      type: object
      properties:
        trxId:
          type: string
          description: 트랜잭션 아이디
        subTrxId:
          type: string
          description: 하위 트랜잭션 아이디 (유니크 정보)
        orderId:
          type: string
          description: 주문번호
        status:
          type: string
          description: 상태값
        startTime:
          type: string
          format: date-time
          description: 시작시간
        endTime:
          type: string
          format: date-time
          description: 종료시간
        tookTime:
          type: integer
          format: int64
          description: 소요시간 (초단위)
    SummaryRetryOrderStatusDetail:
      title: Orchestrator에서 발생한 재시도 상세 정보를 조회한다.
      description: Orchestrator에서 발생한 재시도 상세 정보를 조회한다.
      type: object
      properties:
        trxId:
          type: string
          description: 트랜잭션 아이디
        subTrxId:
          type: string
          description: 하위 트랜잭션 아이디 (유니크 정보)
        orderId:
          type: string
          description: 주문번호
        errorType:
          type: string
          description: 오류타입
        errorMessage:
          type: string
          description: 오류 메시지
        errorStatus:
          type: string
          description: 오류 상태값
        retryCount:
          type: string
          description: 재시도 회수 확인
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (오류발생시간)
    SummaryErrorOrderStatusDetail:
      title: Orchestrator에서 발생한 오류 상세 정보를 조회한다.
      description: Orchestrator에서 발생한 오류 상세 정보를 조회한다.
      type: object
      properties:
        trxId:
          type: string
          description: 트랜잭션 아이디
        subTrxId:
          type: string
          description: 하위 트랜잭션 아이디 (유니크 정보)
        orderId:
          type: string
          description: 주문번호
        errorType:
          type: string
          description: 오류타입
        errorMessage:
          type: string
          description: 오류 메시지
        errorStatus:
          type: string
          description: 오류 상태값
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (오류발생시간)

    SummaryOrderStatus:
      title: 주문상태 요약정보
      description: 주문상태 요약정보
      type: object
      properties:
        status:
          type: string
          description: 주문상태
        count:
          type: integer
          format: int64
          description: 상태건수
    SummaryOrderStatusForOrderRequest:
      title: 주문요청 상태별 모니터링
      description: 주문요청 상태별 모니터링
      type: object
      properties:
        summaryOrderStatus:
          type: array
          items:
            $ref: '#/components/schemas/SummaryOrderStatus'
    OrderStateDto:
      title: 주문요청 객체
      description: 주문요청 정보를 담기위한 객체 정보
      type: object
      properties:
        trxId:
          type: string
          description: 주문요청 트랜잭션키 (orchestrator에서 부여)
        subTrxId:
          type: string
          description: 주문요청 처리 단계별 유니크 키정보
        orderId:
          type: string
          description: 주문번호
        customerId:
          type: string
          description: 고객아이디
        paymentId:
          type: string
          description: 결제아이디
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
        amount:
          type: integer
          format: int64
        shippingAddress:
          type: integer
          description: 배송지주소
        currentState:
          type: string
          description: 현재 주문 처리 상태, 처음 요청시 ORDER_REQUEST
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (주문요청시간)
    ProductDto:
      title: 상품정보 객체
      description: 상품정보 정보를 담기위한 객체 정보
      type: object
      properties:
        productId:
          type: string
          description: 상품정보 아이디
        itemId:
          type: string
          description: 상품아이템 아이디
        count:
          type: integer
          format: int64
          description: 상품주문수량
    CouponDto:
      title: 쿠폰상세정보 객체
      description: 쿠폰상세정보 정보를 담기위한 객체 정보
      type: object
      properties:
        couponType:
          type: string
          description: 쿠폰타입(상품쿠폰, 배송쿠폰, 장바구니쿠폰 등)
        couponId:
          type: string
          description: 쿠폰아이디
    OrderCancelStateDto:
      title: 주문취소요청 객체
      description: 주문취소요청 정보를 담기위한 객체 정보
      type: object
      properties:
        trxId:
          type: string
          description: 주문취소요청 트랜잭션키 (orchestrator에서 부여)
        subTrxId:
          type: string
          description: 주문취소요청 처리 단계별 유니크 키정보
        orderId:
          type: string
          description: 주문번호
        customerId:
          type: string
          description: 고객아이디
        paymentId:
          type: string
          description: 결제아이디
        blameType:
          type: string
          description: 귀책사유타입
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 상품목록
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 쿠폰목록
        amount:
          type: integer
          format: int64
          description: 총결제금액
        shippingAddress:
          type: integer
          description: 배송지주소
        currentState:
          type: string
          description: 현재 주문 처리 상태, 처음 요청시 ORDER_REQUEST
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (주문요청시간)
    OrderReturnStateDto:
      title: 반품처리요청 객체
      description: 반품처리요청 정보를 담기위한 객체 정보
      type: object
      properties:
        trxId:
          type: string
          description: 반품처리요청 트랜잭션키 (orchestrator에서 부여)
        subTrxId:
          type: string
          description: 반품처리요청 처리 단계별 유니크 키정보
        orderId:
          type: string
          description: 주문번호
        customerId:
          type: string
          description: 고객아이디
        paymentId:
          type: string
          description: 결제아이디
        blameType:
          type: string
          description: 귀책사유타입
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 상품목록
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 쿠폰목록
        amount:
          type: integer
          format: int64
          description: 총결제금액
        shippingAddress:
          type: integer
          description: 배송지주소
        currentState:
          type: string
          description: 현재 주문 처리 상태, 처음 요청시 ORDER_REQUEST
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (주문요청시간)
    OrderExchangeStateDto:
      title: 교환처리요청 객체
      description: 교환처리요청 정보를 담기위한 객체 정보
      type: object
      properties:
        trxId:
          type: string
          description: 교환처리요청 트랜잭션키 (orchestrator에서 부여)
        subTrxId:
          type: string
          description: 교환처리요청 처리 단계별 유니크 키정보
        orderId:
          type: string
          description: 주문번호
        customerId:
          type: string
          description: 고객아이디
        paymentId:
          type: string
          description: 결제아이디
        blameType:
          type: string
          description: 귀책사유타입
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 상품목록
        coupons:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
          description: 쿠폰목록
        amount:
          type: integer
          format: int64
          description: 총결제금액
        shippingAddress:
          type: integer
          description: 배송지주소
        currentState:
          type: string
          description: 현재 주문 처리 상태, 처음 요청시 ORDER_REQUEST
        eventAt:
          type: string
          format: date-time
          description: 이벤트 발생시간 (주문요청시간)

